name = "SPCSpectra"
uuid = "ddf1bf59-526a-4a23-8a87-8f8ce489e0c9"
authors = ["hhaensel <helmut.haensel@gmx.de>"]
version = "0.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1"
